---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/pages
  label: Pages
  create: all
  match: "**/*"
  new_doc_ext: ".json"
- type: document
  path: content/pages
  label: Page
- type: document
  path: content/posts
  label: Post
- type: directory
  path: content/posts
  label: Posts
  create: documents
  match: "**/*"
- type: document
  path: content/animals
  label: Animal
- type: directory
  path: content/animals
  label: Animals
  create: documents
  match: "**/*"
  templates:
  - animal-info
upload_dir: content/images
public_path: "../images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
